version: '3.7'
services:

    law-php-fpm:
        image: ${REGISTRY}/${PHP_FMP_CONTAINER_NAME}:${IMAGE_TAG}
        volumes:
            - .:/app

    law-php-cli:
        image: ${REGISTRY}/${PHP_CLI_CONTAINER_NAME}:${IMAGE_TAG}
        volumes:
            - .:/app

    law-nginx:
        image: ${REGISTRY}/${NGINX_CONTAINER_NAME}:${IMAGE_TAG}
        ports:
            - ${APP_WEB_PORT}:80
        volumes:
            - .:/app

    law-mariadb:
        image: ${MYSQL_VERSION}
        container_name: law-mariadb
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - .:/app
        ports:
            - ${MYSQL_PORT}:3306
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
